# Generated by Django 4.1.4 on 2022-12-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teste",
        ),
    ]
