# Generated by Django 4.1.4 on 2022-12-19 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="FormaPagamento",
            new_name="FormPayment",
        ),
        migrations.RenameModel(
            old_name="Transacao",
            new_name="Transaction",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="formpayment",
            old_name="ativo",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="formpayment",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="categoria",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="data_transacao",
            new_name="date_transaction",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="descricao",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="forma_pagamento",
            new_name="form_payment",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="tipo_operacao",
            new_name="type_operation",
        ),
    ]
