# Generated by Django 4.1.4 on 2022-12-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endereco",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="cidade",
        ),
    ]
