# Generated by Django 4.1.4 on 2022-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_categoria_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpayment",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Nome"),
        ),
    ]
