# Generated by Django 4.1.4 on 2022-12-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_endereco_bairro_remove_endereco_cidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endereco",
            old_name="pessoa_end",
            new_name="cliente",
        ),
    ]
