# Generated by Django 4.1.4 on 2022-12-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_pessoa_end_endereco_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="formapagamento",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="transacao",
            name="created_by",
        ),
    ]
