# Generated by Django 4.1.4 on 2022-12-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_cliente_created_by_remove_endereco_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='transactions.cliente'),
        ),
    ]
